Définir le chemin pour accéder à tous les fichiers des matchs

In [1]:

import pandas as pd
import json
import os
from pathlib import Path

Data_path = Path('../data/ligue1')

print(len(list(Data_path.glob('*.json'))))

377

Identification des équipes et compter les buts

Permet de récupérer les résultats du match

In [2]:
def resultat_match(fichier_path):
    with open(fichier_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    df = pd.json_normalize(data)

    match_id = Path(fichier_path).stem

    equipes = df[df['type.name'] == 'Starting XI']['team.name'].tolist()

    equipe_domicile = equipes[0]
    equipe_exterieur = equipes[1]

    tirs = df[df['type.name'] == 'Shot']
    buts = tirs[tirs['shot.outcome.name'] == 'Goal']

    buts_domicile = len(buts[buts['team.name'] == equipe_domicile])
    buts_exterieur = len(buts[buts['team.name'] == equipe_exterieur])

    return {'match ID' : match_id, 'equipe_domicile': equipe_domicile, 'equipe_exterieur': equipe_exterieur, 'buts_domicile': buts_domicile, 'buts_exterieur': buts_exterieur}

test_match = Data_path / '3900512.json'
resultat = resultat_match(test_match)

print(f"{resultat['equipe_domicile']} {resultat['buts_domicile']} - {resultat['buts_exterieur']} {resultat['equipe_exterieur']}")

Montpellier 3 - 1 Stade de Reims

Charger tous les matchs

In [3]:
def charger_tous_les_matchs(dossier_path):
    dossier = Path(dossier_path)
    fichiers = list(dossier.glob('*.json'))
    
    resultats = []
    erreurs = []

    for i, fichier in enumerate(fichiers):
        if 'checkpoint' in str(fichier):
            continue
        try:
            resultat = resultat_match(fichier)
            resultats.append(resultat)
        except Exception as e:
            erreurs.append({'fichier': fichier.name, 'erreur': str(e)})

    print(f'{len(resultats)} matchs chargés, {len(erreurs)} erreurs')

    if erreurs:
        print(f"Fichiers avec erreurs : {[e['fichier'] for e in erreurs]}")

    return pd.DataFrame(resultats)

df_matchs = charger_tous_les_matchs(Data_path)

df_matchs.head(10)

377 matchs chargés, 0 erreurs

  match ID equipe_domicile     equipe_exterieur  buts_domicile  buts_exterieur
0  3829413           Lille  Paris Saint-Germain              0               1
1  3829414       Marseille                 Caen              0               1
2  3829415          Bastia               Rennes              2               1
3  3829416        OGC Nice            AS Monaco              1               2
4  3829417          Troyes      Gazélec Ajaccio              0               0
5  3829418          Nantes             Guingamp              0               0
6  3829419     Montpellier               Angers              0               2
7  3829420        Bordeaux       Stade de Reims              1               2
8  3829421        Toulouse        Saint-Étienne              2               1
9  3829422            Lyon              Lorient              0               0

Calculer le classement

In [4]:
def calcul_classement(df_matchs):
    stats = {}

    for i, match in df_matchs.iterrows():
        equipe_dom = match['equipe_domicile']
        equipe_ext = match['equipe_exterieur']
        buts_dom = match['buts_domicile']
        buts_ext = match['buts_exterieur']

        for equipe in [equipe_dom, equipe_ext]:
            if equipe not in stats:
                stats[equipe] = {
                    'Equipe': equipe,
                    'Pts' : 0,
                    'J': 0,
                    'V': 0,
                    'N': 0,
                    'D': 0,
                    'BP': 0,
                    'BC': 0
                }
        stats[equipe_dom]['J'] += 1
        stats[equipe_ext]['J'] += 1

        stats[equipe_dom]['BP'] += buts_dom
        stats[equipe_dom]['BC'] += buts_ext
        stats[equipe_ext]['BP'] += buts_ext
        stats[equipe_ext]['BC'] += buts_dom

        if buts_dom > buts_ext:
            stats[equipe_dom]['Pts'] += 3
            stats[equipe_dom]['V'] += 1
            stats[equipe_ext]['D'] += 1
        elif buts_dom < buts_ext:
            stats[equipe_ext]['Pts'] += 3
            stats[equipe_ext]['V'] += 1
            stats[equipe_dom]['D'] += 1
        else:
            stats[equipe_dom]['Pts'] += 1
            stats[equipe_ext]['Pts'] += 1
            stats[equipe_dom]['N'] += 1
            stats[equipe_ext]['N'] += 1

    df_classement = pd.DataFrame(stats.values())

    df_classement['Diff'] = df_classement['BP'] - df_classement['BC']
    
    df_classement = df_classement.sort_values(by=['Pts', 'Diff', 'BP'], ascending = False)

    df_classement = df_classement.reset_index(drop=True)
    df_classement.index = df_classement.index + 1

    return df_classement

df_classement = calcul_classement(df_matchs)
df_classement

                 Equipe  Pts   J   V   N   D  BP  BC  Diff
1   Paris Saint-Germain   93  37  29   6   2  99  18    81
2                  Lyon   65  38  19   8  11  66  41    25
3             AS Monaco   64  38  17  13   8  54  49     5
4              OGC Nice   63  38  18   9  11  55  39    16
5                 Lille   60  38  15  15   8  38  27    11
6         Saint-Étienne   56  37  16   8  13  39  35     4
7                  Caen   56  38  17   5  16  38  50   -12
8             Marseille   53  38  12  17   9  48  39     9
9                Angers   51  38  13  12  13  40  37     3
10               Rennes   50  38  12  14  12  49  53    -4
11          Montpellier   49  38  14   7  17  46  47    -1
12             Guingamp   47  38  12  11  15  46  52    -6
13               Nantes   47  38  12  11  15  30  42   -12
14             Bordeaux   46  37  11  13  13  45  52    -7
15               Bastia   46  37  12  10  15  32  39    -7
16              Lorient   45  38  11  12  15  46  58   -12
17             Toulouse   39  38   9  12  17  43  54   -11
18       Stade de Reims   38  38   9  11  18  43  55   -12
19      Gazélec Ajaccio   36  37   8  12  17  34  53   -19
20               Troyes   19  37   3  10  24  25  76   -51

In [9]:
import sys
sys.path.append('../scripts')
import fonction

df_matchs = charger_tous_les_matchs('../data/ligue1')
df_classement = calcul_classement(df_matchs)
df_classement.to_csv('../outputs/classement_ligue1.csv', index=True)

377 matchs chargés, 0 erreurs